import { StyleSheet } from "react-native";
import { appColors } from "../../const/app-colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: appColors.slate100,
  },
  headerBanner: {
    backgroundColor: appColors.white,
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: appColors.slate200,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 12,
  },
  headerBannerPhone: {
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  badgeShield: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: appColors.blue50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: appColors.slate900,
  },
  adminRoleTag: {
    backgroundColor: appColors.blue200,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  adminRoleTagText: {
    fontSize: 11,
    fontWeight: '700',
    color: appColors.blue700,
  },
  headerSubtitle: {
    fontSize: 12,
    color: appColors.slate500,
    marginTop: 2,
  },
  subTabNav: {
    flexDirection: 'row',
    backgroundColor: appColors.slate100,
    borderRadius: 12,
    padding: 4,
    gap: 4,
  },
  subTabBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  subTabBtnActive: {
    backgroundColor: appColors.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  subTabBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: appColors.slate600,
  },
  subTabBtnTextActive: {
    color: appColors.blue600,
    fontWeight: '700',
  },
  scrollBody: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    gap: 16,
  },
  scrollContentTablet: {
    padding: 24,
  },
  actionCard: {
    backgroundColor: appColors.white,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: appColors.slate200,
  },
  actionCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 12,
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: appColors.slate800,
  },
  cardDesc: {
    fontSize: 12,
    color: appColors.slate500,
    marginTop: 2,
  },
  scanCameraBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: appColors.blue600,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
  },
  scanCameraBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: appColors.white,
  },
  quickPickLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: appColors.slate600,
    marginTop: 14,
    marginBottom: 8,
  },
  userChipsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  userChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: appColors.slate50,
    borderWidth: 1,
    borderColor: appColors.slate200,
    minWidth: 140,
  },
  userChipSelected: {
    backgroundColor: appColors.blue50,
    borderColor: appColors.blue600,
  },
  userChipAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: appColors.blue200,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  userChipAvatarImg: {
    width: '100%',
    height: '100%',
  },
  userChipAvatarText: {
    fontSize: 12,
    fontWeight: '700',
    color: appColors.blue600,
  },
  userChipName: {
    fontSize: 12,
    fontWeight: '600',
    color: appColors.slate800,
    maxWidth: 90,
  },
  userChipNameSelected: {
    color: appColors.blue700,
  },
  userChipMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 1,
  },
  userChipCode: {
    fontSize: 10,
    color: appColors.slate500,
  },
  miniStatusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  detailRowLayout: {
    flexDirection: 'column',
    gap: 16,
  },
  detailRowLayoutTablet: {
    flexDirection: 'row',
  },
  colSection: {
    gap: 16,
  },
  card: {
    backgroundColor: appColors.white,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: appColors.slate200,
  },
  profileHeader: {
    flexDirection: 'row',
    gap: 14,
  },
  avatarLargeWrapper: {
    width: 68,
    height: 68,
    borderRadius: 34,
    overflow: 'hidden',
    backgroundColor: appColors.slate100,
    borderWidth: 2,
    borderColor: appColors.blue200,
  },
  avatarLarge: {
    width: '100%',
    height: '100%',
  },
  avatarPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: appColors.blue50,
  },
  avatarPlaceholderText: {
    fontSize: 26,
    fontWeight: '700',
    color: appColors.blue600,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  profileName: {
    fontSize: 16,
    fontWeight: '700',
    color: appColors.slate900,
  },
  profileCode: {
    fontSize: 12,
    color: appColors.slate500,
    marginTop: 2,
  },
  phoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 4,
  },
  phoneText: {
    fontSize: 12,
    color: appColors.slate600,
  },
  roomZoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 4,
  },
  roomZoneText: {
    fontSize: 12,
    color: appColors.blue700,
    fontWeight: '500',
  },
  currentStatusRow: {
    marginTop: 8,
  },
  conditionPill: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
  },
  conditionPillText: {
    fontSize: 11,
    fontWeight: '700',
  },
  noteBox: {
    marginTop: 12,
    padding: 10,
    borderRadius: 8,
    backgroundColor: appColors.slate50,
    borderWidth: 1,
    borderColor: appColors.slate200,
  },
  noteBoxLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: appColors.slate500,
  },
  noteBoxText: {
    fontSize: 12,
    color: appColors.slate700,
    marginTop: 2,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  historyItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: appColors.slate100,
  },
  historySessionName: {
    fontSize: 13,
    fontWeight: '600',
    color: appColors.slate800,
  },
  historyMeta: {
    fontSize: 11,
    color: appColors.slate500,
    marginTop: 2,
  },
  historyStatusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  historyPresent: {
    backgroundColor: appColors.green50,
  },
  historyVerify: {
    backgroundColor: appColors.red50,
  },
  historyMissing: {
    backgroundColor: appColors.amber50,
  },
  historyStatusText: {
    fontSize: 11,
    fontWeight: '600',
  },
  textGreen: {
    color: appColors.green700,
  },
  textRed: {
    color: appColors.red700,
  },
  textAmber: {
    color: appColors.amber600,
  },
  emptyBox: {
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyText: {
    fontSize: 12,
    color: appColors.slate400,
    marginTop: 8,
    textAlign: 'center',
  },
  updateFormCard: {
    borderColor: appColors.blue200,
  },
  fieldLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: appColors.slate700,
    marginBottom: 8,
  },
  statusChipsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  statusOptionChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    gap: 6,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  statusOptionText: {
    fontSize: 12,
  },
  noteInput: {
    borderWidth: 1,
    borderColor: appColors.slate200,
    borderRadius: 10,
    padding: 10,
    fontSize: 12,
    color: appColors.slate800,
    backgroundColor: appColors.slate50,
    minHeight: 70,
    textAlignVertical: 'top',
  },
  submitUpdateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: appColors.blue600,
    paddingVertical: 12,
    borderRadius: 12,
    marginTop: 14,
  },
  submitUpdateBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: appColors.white,
  },
  logItem: {
    flexDirection: 'row',
    gap: 10,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: appColors.slate100,
  },
  logTimelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: appColors.blue600,
    marginTop: 4,
  },
  logContent: {
    flex: 1,
  },
  logTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  logTime: {
    fontSize: 11,
    fontWeight: '600',
    color: appColors.slate600,
  },
  logAdmin: {
    fontSize: 11,
    color: appColors.slate400,
  },
  logTransitionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 4,
  },
  logTag: {
    fontSize: 12,
  },
  logNoteText: {
    fontSize: 11,
    fontStyle: 'italic',
    color: appColors.slate600,
    marginTop: 4,
  },
  emptySelectBox: {
    backgroundColor: appColors.white,
    padding: 40,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: appColors.slate200,
  },
  emptySelectTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: appColors.slate700,
    marginTop: 12,
  },
  emptySelectDesc: {
    fontSize: 13,
    color: appColors.slate500,
    textAlign: 'center',
    marginTop: 6,
    maxWidth: 400,
  },
  userListContainer: {
    flex: 1,
    padding: 16,
  },
  userListTopBar: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  searchBarWrap: {
    flex: 1,
    minWidth: 200,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: appColors.white,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: appColors.slate200,
    gap: 8,
    height: 44,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    color: appColors.slate800,
  },
  userActionBtns: {
    flexDirection: 'row',
    gap: 8,
  },
  batchAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: appColors.blue50,
    borderWidth: 1,
    borderColor: appColors.blue200,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
  },
  batchAddBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: appColors.blue600,
  },
  addUserSingleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: appColors.blue600,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
  },
  addUserSingleBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: appColors.white,
  },
  filterChipsRow: {
    marginTop: 12,
    marginBottom: 8,
  },
  filterRowInner: {
    flexDirection: 'row',
    gap: 8,
  },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    backgroundColor: appColors.white,
    borderWidth: 1,
    borderColor: appColors.slate200,
  },
  filterChipActive: {
    backgroundColor: appColors.blue50,
    borderColor: appColors.blue600,
  },
  filterChipText: {
    fontSize: 12,
    color: appColors.slate600,
    fontWeight: '500',
  },
  filterChipTextActive: {
    color: appColors.blue600,
    fontWeight: '700',
  },
  usersListContent: {
    paddingTop: 8,
    paddingBottom: 24,
    gap: 8,
  },
  userListItemCard: {
    flex: 1,
    margin: 4,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: appColors.white,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: appColors.slate200,
    gap: 12,
  },
  userListAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: appColors.blue50,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  userListAvatarImg: {
    width: '100%',
    height: '100%',
  },
  userListAvatarText: {
    fontSize: 16,
    fontWeight: '700',
    color: appColors.blue600,
  },
  userListItemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
  },
  userListItemName: {
    fontSize: 14,
    fontWeight: '600',
    color: appColors.slate900,
    flex: 1,
  },
  conditionPillSmall: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    borderWidth: 1,
  },
  conditionPillSmallText: {
    fontSize: 10,
    fontWeight: '700',
  },
  userListItemCode: {
    fontSize: 11,
    color: appColors.slate500,
    marginTop: 2,
  },
  userListItemRoom: {
    fontSize: 11,
    color: appColors.blue600,
    marginTop: 2,
  },
  reportFormRow: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 16,
    flexWrap: 'wrap',
  },
  monthChipsRow: {
    flexDirection: 'row',
    gap: 6,
  },
  monthChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: appColors.slate100,
  },
  monthChipActive: {
    backgroundColor: appColors.blue600,
  },
  monthChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: appColors.slate600,
  },
  monthChipTextActive: {
    color: appColors.white,
  },
  yearChipsRow: {
    flexDirection: 'row',
    gap: 6,
  },
  yearChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: appColors.slate100,
  },
  yearChipActive: {
    backgroundColor: appColors.blue600,
  },
  yearChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: appColors.slate600,
  },
  yearChipTextActive: {
    color: appColors.white,
  },
  roomChipsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  roomFilterChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    backgroundColor: appColors.slate100,
  },
  roomFilterChipActive: {
    backgroundColor: appColors.blue50,
    borderWidth: 1,
    borderColor: appColors.blue600,
  },
  roomFilterChipText: {
    fontSize: 12,
    color: appColors.slate600,
    fontWeight: '600',
  },
  roomFilterChipTextActive: {
    color: appColors.blue600,
  },
  metricsRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 20,
  },
  metricCard: {
    flex: 1,
    backgroundColor: appColors.slate50,
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: appColors.slate200,
  },
  metricValue: {
    fontSize: 20,
    fontWeight: '800',
    color: appColors.blue600,
  },
  metricLabel: {
    fontSize: 11,
    color: appColors.slate500,
    marginTop: 4,
    textAlign: 'center',
  },
  exportBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: appColors.green600,
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 20,
  },
  exportBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: appColors.white,
  },
});
